import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import AppShell, { ErrorState, LoadingState } from "../components/AppShell";
const LANGUAGE_LABELS = { cpp: "C++", java: "Java", python: "Python" };
const DSAHistoryPage = () => {
  const navigate = useNavigate(); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { const fetchHistory = async () => { try { setLoading(true); const token = localStorage.getItem("token"); const response = await axios.get("http://localhost:8000/api/dsa/history", { headers: { Authorization: `Bearer ${token}` } }); setHistory(response.data); } catch (error) { setMessage(error.response?.data?.message || "Unable to load DSA assessment history"); } finally { setLoading(false); } }; fetchHistory(); }, []);
  if (loading) return <LoadingState label="Loading assessment history..." />; if (message) return <ErrorState message={message} />;
  return <AppShell><main className="page-container"><div className="page-header"><div><p className="eyebrow">Coding archive</p><h1 className="page-title">Assessment history</h1><p className="page-copy">Track your problem-solving performance across languages and attempts.</p></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={() => navigate("/dashboard")}>← Dashboard</button><button className="btn btn-primary" onClick={() => navigate("/dsa/setup")}>New assessment</button></div></div>{history.length === 0 ? <div className="card py-16 text-center"><p className="font-display text-2xl">No completed assessments yet</p><p className="mt-2 text-sm text-slate-500">Your coding reports will appear here.</p><button className="btn btn-primary mt-6" onClick={() => navigate("/dsa/setup")}>Start your first assessment</button></div> : <div className="grid gap-4 md:grid-cols-2">{history.map((result, index) => <article className="card" key={result._id}><div className="flex items-start justify-between"><div><span className="badge">{LANGUAGE_LABELS[result.language] || result.language}</span><h2 className="mt-3 font-display text-2xl">Assessment {String(history.length - index).padStart(2, "0")}</h2></div><div className="text-right"><strong className="font-display text-3xl font-normal">{result.overallScore}</strong><span className="text-sm text-slate-400">/100</span></div></div><div className="mt-6 grid grid-cols-2 gap-4 border-y border-line py-4 text-sm"><div><span className="block text-xs text-slate-400">Duration</span><strong>{result.dsaSession?.durationMinutes || 90} minutes</strong></div><div><span className="block text-xs text-slate-400">Completed</span><strong>{new Date(result.dsaSession?.completedAt || result.createdAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</strong></div></div><button className="mt-5 flex w-full items-center justify-between text-sm font-bold text-navy" onClick={() => navigate(`/dsa/result/${result._id}`)}>Open detailed report <span>→</span></button></article>)}</div>}</main></AppShell>;
};
export default DSAHistoryPage;
