import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import axios from "axios";
import AppShell, { ErrorState, LoadingState } from "../components/AppShell";
const ReviewList = ({ title, items }) => <section className="card"><h2 className="font-display text-xl">{title}</h2>{items?.length ? <ul className="mt-4 space-y-3">{items.map((item, index) => <li className="flex gap-3 text-sm leading-6 text-slate-600" key={index}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-rust" />{item}</li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No notes provided.</p>}</section>;
const DSAResultPage = () => {
  const { resultId } = useParams(); const navigate = useNavigate(); const [result, setResult] = useState(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { const fetchResult = async () => { try { const token = localStorage.getItem("token"); const response = await axios.get(`http://localhost:8000/api/dsa/result/${resultId}`, { headers: { Authorization: `Bearer ${token}` } }); setResult(response.data); } catch (error) { setMessage(error.response?.data?.message || "Unable to load DSA result"); } finally { setLoading(false); } }; fetchResult(); }, [resultId]);
  if (loading) return <LoadingState label="Preparing assessment report..." />; if (message) return <ErrorState message={message} />; if (!result) return <ErrorState message="DSA result not found." />;
  return <AppShell><main className="page-container"><div className="page-header"><div><p className="eyebrow">Assessment report</p><h1 className="page-title">Coding performance</h1><p className="page-copy">Language: <strong className="text-ink">{result.language}</strong></p></div><div className="flex items-center gap-5"><div className="text-right"><span className="block text-xs font-bold uppercase tracking-wider text-slate-400">Overall score</span><strong className="font-display text-4xl font-normal">{result.overallScore}<small className="text-lg text-slate-400">/100</small></strong></div><button className="btn btn-secondary" onClick={() => navigate("/dsa/history")}>History</button></div></div><section><div className="mb-4"><p className="eyebrow">Question review</p><h2 className="section-title">How each solution performed</h2></div><div className="space-y-4">{result.questionEvaluations?.map((evaluation, index) => <article className="card" key={evaluation.question?._id || index}><div className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-5"><div><span className="text-xs font-bold uppercase tracking-wider text-slate-400">Question {index + 1}</span><h3 className="mt-1 font-display text-xl">{evaluation.question?.title || "DSA Question"}</h3><span className="badge mt-2">{evaluation.question?.difficulty || "Not available"}</span></div><strong className="font-display text-3xl font-normal">{evaluation.score}<small className="text-sm text-slate-400">/100</small></strong></div><div className="mt-5 grid gap-x-8 gap-y-5 md:grid-cols-2">{[["Correctness", evaluation.correctness], ["Approach", evaluation.approach], ["Time complexity", evaluation.timeComplexity], ["Space complexity", evaluation.spaceComplexity], ["Code quality", evaluation.codeQuality], ["Edge cases", evaluation.edgeCases]].map(([label, value]) => <div key={label}><h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</h4><p className="mt-1 text-sm leading-6 text-slate-600">{value || "No review available."}</p></div>)}</div><div className="mt-5 border-l-2 border-rust bg-slate-50 p-4"><strong className="block text-sm">Evaluator feedback</strong><p className="mt-1 text-sm leading-6 text-slate-600">{evaluation.feedback || "No feedback available."}</p></div></article>)}</div></section><div className="mt-8 grid gap-4 lg:grid-cols-3"><ReviewList title="Strengths" items={result.strengths} /><ReviewList title="Areas to improve" items={result.weaknesses} /><ReviewList title="Suggestions" items={result.suggestions} /></div><section className="card mt-4"><p className="eyebrow">Final note</p><h2 className="section-title">Overall feedback</h2><p className="mt-4 text-sm leading-7 text-slate-600">{result.feedback || "No overall feedback provided."}</p><div className="mt-6 flex justify-end"><button className="btn btn-primary" onClick={() => navigate("/dsa/setup")}>Try another assessment</button></div></section></main></AppShell>;
};
export default DSAResultPage;
